get and show cmdline when earlyomm kill a process
rfjakob/earlyoom pull request #299
Opened 2023-09-13 06:09 UTC by RanHuang

There are multiple java processes in my system. When earlyoom determines to kill a process, the process name is just 'java'. I need more information about the killed java process. e.g: 
* run earlyoom without get-cmdline
![image](https://github.com/rfjakob/earlyoom/assets/6802708/b62cc932-803f-4e5f-8be1-459292fc0c7d)

* run earlyoom with get-cmdline
![image](https://github.com/rfjakob/earlyoom/assets/6802708/a8e6bd73-d250-4ef3-aa35-12b3d5f98ca9)

2023-09-13 06:23 UTC, RanHuang commented
#264

2023-09-14 05:55 UTC, rfjakob requested changes
Nice, thank you! A few details to change, please

2023-09-14 05:55 UTC, rfjakob commented on MANPAGE.md
> +### \-\-get-cmdline
No need for a flag - let's just have it enabled all the time.

2023-09-14 05:55 UTC, rfjakob commented on meminfo.c
> +    /* replace new line charater with space */
Comment should be: "replace null character with space"

2023-09-14 05:55 UTC, rfjakob commented on meminfo.c
> +    // Strip trailing newline
Comment should be: "Strip trailing space"

2023-09-14 05:55 UTC, rfjakob commented on testsuite_unit_test.go
> +	t.Logf("process name %q", comm)
Should be "process cmdline" here

2023-09-14 08:18 UTC, RanHuang commented
I've fixed all the issues

2023-09-15 17:38 UTC, rfjakob requested changes

2023-09-15 17:38 UTC, rfjakob commented on kill.c
> +        }
Move after the if block, not inside

2023-09-15 17:38 UTC, rfjakob commented on kill.c
> +        }
We don't need cmdline yet, remove here and only do this once, at the end of the function.

2023-09-15 17:38 UTC, rfjakob commented on testsuite_cli_test.go
> +const rssMaxKiB = 4096
This is a different topic, please remove from this pull request

2023-09-18 19:39 UTC, merged

2023-09-18 19:39 UTC, rfjakob commented
Merged, thanks!