earlyoom.service: add Conflicts
rfjakob/earlyoom pull request #306
Opened 2024-02-08 11:18 UTC by yangfl

Some distros default to systemd oom handling. Mark systemd unit conflict with other oom handlers to prevent incompatibility.

2024-02-18 20:17 UTC, Mikaela requested changes
At least on my quick testing with similar drop-in config on Fedora 39 and 40, not including the socket as a conflict caused systemd-oomd.service to be constantly started and stopped every few seconds.

I am not sure if I had manually enabled either or not, but I think better safe than sorry.

2024-02-18 20:17 UTC, Mikaela commented on earlyoom.service.in
> +Conflicts=systemd-oomd.service nohang.service oomd.service
```suggestion
Conflicts=systemd-oomd.service systemd-oomd.socket nohang.service oomd.service
```

2024-02-26 10:00 UTC, hakavlad commented
missing nohang-desktop.service

2024-02-26 10:08 UTC, hakavlad commented
IMHO 'Conflicts' option creates unexpected behavior when starting one server stops another. But I don't know which solution is optimal.

2024-02-26 10:20 UTC, hakavlad commented
>conflict with other oom handlers to prevent incompatibility.

This is not necessarily incompatibility: just one killer will work before the other.

2024-02-28 09:49 UTC, rfjakob commented
Yeah, not sure about this. Having multiple oom handlers is strange, but can still work.

A warning would be enough. Is there a way to have systemd warn about it but not prevent it?

2024-04-07 19:52 UTC, closed without merging